#!/bin/bash
# ENHANCED AI FRAMEWORK MONITOR
# Purpose: Prevent future branch monitoring blindspots
# Auto-updates CURRENT_TASK.md with real branch activity

echo "🤖 ENHANCED AI FRAMEWORK MONITOR"
echo "================================="

# Run branch monitor
./.ai-framework/branch-monitor.sh

# Extract key metrics
TOTAL_BRANCHES=$(git branch -r | grep -E "origin/claude/" | grep -v HEAD | wc -l | tr -d ' ')
RECENT_COMMITS=$(git log --all --since="24 hours ago" --oneline | grep -E "claude/" | wc -l | tr -d ' ')
LATEST_COMPLETION=$(git log --all --since="48 hours ago" --grep="Complete\|Implement\|Finish\|Done" --oneline | head -1)

echo
echo "📊 AUTO-UPDATING FRAMEWORK STATUS..."

# Auto-update CURRENT_TASK.md with latest metrics
cat > .ai/FRAMEWORK_STATUS.md << EOF
# 🤖 AI FRAMEWORK STATUS (Auto-Updated)
**Last Updated:** $(date '+%Y-%m-%d %H:%M:%S')

## 📊 LIVE METRICS
- **Active Claude Branches:** $TOTAL_BRANCHES
- **Recent Commits (24h):** $RECENT_COMMITS
- **Latest Activity:** $(date '+%H:%M:%S')

## 🔍 LATEST COMPLETION DETECTED:
$LATEST_COMPLETION

## 🛠️ FRAMEWORK STATUS
✅ **Branch Monitoring:** Active
✅ **Cross-Branch Tracking:** Operational
✅ **Auto-Updates:** Functioning
✅ **Blindspot Prevention:** Enabled

## 📈 RECENT BRANCH ACTIVITY
$(git log --all --since="6 hours ago" --format="- %cr: %s" | head -10)

---
*Auto-generated by enhanced-monitor.sh*
EOF

echo "✅ Framework status updated: .ai/FRAMEWORK_STATUS.md"

# Check if there's new completion activity
if [ ! -z "$LATEST_COMPLETION" ]; then
    echo "🎉 NEW COMPLETION DETECTED!"
    echo "   $LATEST_COMPLETION"

    # Update main task status if major completion found
    if echo "$LATEST_COMPLETION" | grep -q "Complete\|Phase"; then
        echo "🔄 Major completion detected - framework should be notified"

        # Add completion alert to CURRENT_TASK.md
        echo "" >> .ai/CURRENT_TASK.md
        echo "## 🚨 LATEST COMPLETION ALERT" >> .ai/CURRENT_TASK.md
        echo "**Detected:** $(date '+%Y-%m-%d %H:%M:%S')" >> .ai/CURRENT_TASK.md
        echo "$LATEST_COMPLETION" >> .ai/CURRENT_TASK.md
        echo "" >> .ai/CURRENT_TASK.md
    fi
fi

echo "🔄 Enhanced monitoring cycle complete."

# Generate monitoring summary
echo
echo "📋 MONITORING SUMMARY:"
echo "├── Active Branches: $TOTAL_BRANCHES"
echo "├── Recent Activity: $RECENT_COMMITS commits"
echo "├── Framework Status: ✅ Operational"
echo "└── Blindspot Risk: ❌ Prevented"
echo